# -------------------------
# Database Config
# -------------------------
DATABASE_URL = "postgresql://postgres:Medical%402025%40IIT_KHARAGPUR@db.napuezfgkzkcdusqkcdh.supabase.co:5432/postgres"

DB_HOST = "db.napuezfgkzkcdusqkcdh.supabase.co"
DB_PORT = "5432"
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "Medical@2025@IIT_KHARAGPUR"

# -------------------------
# SMTP Config
# -------------------------
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "lowcostsolarmedicaldiagnosis@gmail.com"
SMTP_PASS = "hocz lrdu tooc qwzu"

# -------------------------
# Google Service Account (nested table)
# -------------------------
[GOOGLE_SERVICE_ACCOUNT_JSON]
type = "service_account"
project_id = "lowcostmedical"
private_key_id = "9f22e14d95bbedb4daf817b2ee0e5e13358c0a71"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCsl58lhY+cs8ww
s8QVm2JgWbfu4umemuQW9Mb9tx2RH7w/OyVwm16kjJfAC8JHS/om7ClmhpPkRGDY
l8OaUVvEBLsJaBnaxMBy4FyBkq7KwY6JMzSUJadofKHY3DrpViZsjTO3eU8ZSBeC
PyUm73PICOJV4DNLr+Fuj3oKAGi+6P5GNOJ7TtpNY+IhfEiKlTZKhXiWuk7gDcRo
2f9wna2pdFYabZRxbGR0G+R5To+7fxI1AvruVfWDh2h/Dy2yFfMsvOd0nsp4LE5a
kO8lDHRVh5cY5S0QgIOryjAbw9JGVdM9UDKFGiqcV/6VhcZzJVHFFlgPHMAEcXm7
0z71lgGXAgMBAAECggEAEk8cspX3moUMV+z0voy2+UerQSv7N+MbPUAxopVRYqV+
NSr+GXMHWDy96xaUQTdTIzE8YcRMXhPO6PXjPzSln9Fsp155bQF1n6TOIMTBxtU/
sgL870ELVa9FsBlfeoS0G3c4kZx3LVRo111W1fQ4UR54JuoGJwpScjBwSYKqRKOK
3NIM4rhSNqXQn+PH25Z6wkQzGWGtpybbdnJeM9L3xyoPsKtifFMIeacnvc8zDGoV
96XRVDf2pSuw+ls8eALvc5BE+r+R/MzuDU5qeAEeLEjPvbHmvUE0AsgkyCHKCjbA
EBWhqpjkXI6oARKTC1R67np+xEYVQHrJxqaMWPlGaQKBgQDgUHqW6X5ObOy/f2OJ
pVUfyMLicqWWf+5P2jL3nOQaiVi/WZL2V94G6nXKEH6cQ6Ipn/Nu1qy2Gq6btQHC
63ECoTs8TeC6/JhXDCbBmnjG+lwt+sJ5IUSPfzLs7yOZJlxfaMHDbpwPL5zntdPD
c/YsEwS+EjPaX8QGaEeAJLKOYwKBgQDE+Myn3d6NtPDF/94onFR8pg5XPVMYf/ew
dKmI/f2QJnWZkvI9SvPOOZ+SNJzokh/cma8GYKToXolbVqGujnN4bMhVuSbUS7yc
Yjhaf3vrm4wtp+NgloHVHxJKADWnSNFkW9ovsjrVpHd2koTzCCMfDoziqKqJqlJ3
POaMha/cPQKBgQCYf75IGOfI057Etgtqyd8sY6Wyo/TVc5YF7bcWxjABpnySYoha
N/R3STDZNguNmyGFIPwzz3jNuSgaLZ3L8Zr8Cbcm0V9GYHIFQ/qZRrZzuEOw8rkB
9s8Qq45orE/MT9se9i48+lbYsCsBEImuaIjk/+0Kd3+PJ+ox3PU3Nju6NwKBgB47
fdYKJN2lNwt88VFUZVdYeX0EaZuqEI9h6J+hNGkKriQrPMkRlwhBKe/b6XV88C0A
3a9h6A3ObNC7JEfRj4GdWMZni8Er+sAaB0JErPWFw2dCjJDHqRfYFAuNqq6Ja7I2
su99MLCX9MobRRK0XgenSRKFBt/oZ43rqAtLfamVAoGBAIFJrxXUR5PCRlaC/PNj
ZunoPNRSXIxNrDSb+5MECtQNLGLF6U0ieIkawLrLozkhDc9Bs25JpSsq5Sr9q/Mn
NAQtyf+cTa1jjYxK0dNe077c21eqSm/8xVQMAN+mYVh8eHEWb6M07hT+btw/CrBY
f3TQVYmuLQy2ch+6btzaa5mw
-----END PRIVATE KEY-----"""
client_email = "lowcostmedical@lowcostmedical.iam.gserviceaccount.com"
client_id = "110989806377308352874"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/lowcostmedical%40lowcostmedical.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# -------------------------
# Google Sheets
# -------------------------
GOOGLE_SHEET_NAME = "Low Cost Medical"

